version: '2'
services:
  api:
    container_name: dynchan
    build: .
    ports:
      - "8080:8080"
    environment:
      - "DYNCHAN_DATABASE_DIALECT=mysql"
      - "DYNCHAN_DATABASE_CONNECTION=dynchan:4EtjV_tkpaGKbf@tcp(db:3306)/dynchan"
    links:
      - db
    depends_on:
      - db
  db:
    image: mariadb
    expose:
      - 3306
    environment:
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"
      - "MYSQL_DATABASE=dynchan"
      - "MYSQL_USER=dynchan"
      - "MYSQL_PASSWORD=4EtjV_tkpaGKbf"
