version: '2'
services:
  api:
    container_name: dynchan_api
    build: .
    ports:
      - "8080:8080"
    environment:
      - "DYNCHAN_DATABASE_DIALECT=mysql"
      - "DYNCHAN_DATABASE_CONNECTION=dynchan:4EtjV_tkpaGKbf@database/dynchan"
    links:
      - database
    depends_on:
      - database

  database:
    container_name: dynchan_database
    image: mariadb
    ports:
      - "3306"
    environment:
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"
      - "MYSQL_DATABASE=dynchan"
      - "MYSQL_USER=dynchan"
      - "MYSQL_PASSWORD=4EtjV_tkpaGKbf"
